language: python

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

install: 
    - pip install pyserial
    - pip install wheel
    - git submodule update --init --recursive
    - pip install .

matrix:
    allow_failures:
        - python: 3.3
        - python: 3.4
        - python: 3.5

script:
    - python -m unittest discover -v sunspec
    - python -m pip wheel --wheel-dir dist --no-deps .
    - python setup.py sdist

addons:
    artifacts: true
    paths:
    - dist/*


notifications:
    email: false
