environment:
  global:
    PYTHON: "C:\\Python36"

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}

build_script:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python -m pip install --upgrade pip setuptools wheel
  - python -m pip install --user virtualenv
  - git submodule update --init
  - python -m pip install -e .
  - python -m unittest discover -v sunspec
  - python -m pip wheel --wheel-dir dist --no-deps .
  - python setup.py sdist
  - ps: Update-AppveyorBuild -Version "v$(venv\\Scripts\\python -c 'import sunspec; print(sunspec.__version__, end=\"\")') b$Env:APPVEYOR_BUILD_NUMBER"

artifacts:
  - path: 'dist/*'

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_finish:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}

